version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 989615686095.dkr.ecr.ap-southeast-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
  build:
    commands:
      - echo Building Docker image...
      - docker build -t 989615686095.dkr.ecr.ap-southeast-1.amazonaws.com/my-app:$IMAGE_TAG .
      - docker tag 989615686095.dkr.ecr.ap-southeast-1.amazonaws.com/my-app:$IMAGE_TAG 989615686095.dkr.ecr.ap-southeast-1.amazonaws.com/my-app:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 989615686095.dkr.ecr.ap-southeast-1.amazonaws.com/my-app:$IMAGE_TAG
      - docker push 989615686095.dkr.ecr.ap-southeast-1.amazonaws.com/my-app:latest
      - printf '[{"name":"my-app","imageUri":"%s"}]' 989615686095.dkr.ecr.ap-southeast-1.amazonaws.com/my-app:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
